# Copyright (c) 2022 Espresso Systems (espressosys.com)
#
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If
# not, see <https:#www.gnu.org/licenses/>.

[meta]
FORMAT_VERSION = "0.1.0"

HTML_TOP = """
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <title>{{NAME}} Reference</title>
    <link rel='stylesheet' href='/public/css/style.css'>
    <script src='/public/js/script.js'></script>
    <link rel='icon' type='image/svg+xml'
     href='/public/favicon.svg'>
  </head>
  <body>
    <div><a href='https://espressosys.com'><img src='/public/espressosys_logo.svg'
              alt='Espresso Systems Logo'
              /></a></div>
    <h1>{{NAME}} API {{FORMAT_VERSION}} Reference</h1>
    <p>{{DESCRIPTION}}</p>
"""

HTML_BOTTOM = """
    <h1>&nbsp;</h1>
    <p>Copyright © 2022 Espresso Systems. All rights reserved.</p>
  </body>
</html>
"""

HEADING_ENTRY = "<a name='{{NAME}}'><h3 class='entry'><span class='meth'>{{METHOD}}</span> {{NAME}}</h3></a>\n"
HEADING_ROUTES = "<h3>Routes</h3>\n"
HEADING_PARAMETERS = "<h3>Parameters</h3>\n"
HEADING_DESCRIPTION = "<h3>Description</h3>\n"

ROUTE_PATH = "<p class='path'><a href='{{PATH}}'>{{PATH}}</a></p>\n"

PARAMETER_TABLE_OPEN = "<table>\n"
PARAMETER_TABLE_CLOSE = "</table>\n\n"
PARAMETER_ROW = "<tr><td class='parameter'>{{NAME}}</td><td class='type'>{{TYPE}}</td></tr>\n"
PARAMETER_NONE = "<div class='meta'>None</div>"

# TODO Maybe refactor to eliminate redundancy with HTML_TOP and HTML_BOTTOM
MINIMAL_HTML = """
<!doctype html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <link rel='stylesheet' href='/public/css/style.css'>
    <title>{{TITLE}}</title>
    <link rel='icon' type='image/svg+xml'
     href='/public/favicon.svg'>
  </head>
  <body>
    <div><img src='/public/espressosys_logo.svg'
              alt='Espresso Systems Logo'
              /></div>
    <h1>{{TITLE}}</h1>
    {{BODY}}
    <h1>&nbsp;</h1>
    <p>Copyright © 2022 Espresso Systems. All rights reserved.</p>
  </body>
</html>
"""

[route.insert_pubkey]
PATH = ["/insert_pubkey"]
# TODO Why is this POST and not PUT?
METHOD = "POST"
# TODO Replace the example with a real example of the JSON serialization
DOC = """
Insert a user public key for a signed public key address. Fails with status 400 Bad Request if
key deserialization or the signature check fail.

The request body must be a JSON serialization of struct InsertPubKey, e.g.
{ pub_key_bytes = [ 221, 132, 0, ... ], sig = [ 67, 24, 153, 251, ... ] }
"""

[route.request_pubkey]
PATH = ["/request_pubkey"]
METHOD = "POST"
# TODO Replace the example with a real example of the JSON serialization
DOC = """
Lookup a user public key from a Jellyfish CAP user address. Responds with status 404 Not Found if no
public key has been inserted for the given address. Fails with status 400 Bad Request if key
deserialization or the signature check fail.

The request body must be a JSON serialization of Jellyfish CAP Signature, e.g.
{ }
"""

[route.request_peers]
PATH = ["/request_peers"]
METHOD = "GET"
# TODO Describe the purpose of this route.
# TODO Describe the response of this route.
DOC = """
Fetch all the public key bundles for all peers. Fails with status 500 Internal Server Error if
storage cannot be read.
"""
