stages:
  - build

variables:
  BRANCH: $CI_COMMIT_BRANCH
  CONTAINER_IMAGE: zerok_lib
  DOCKER_REGISTRY: 279906117593.dkr.ecr.us-east-2.amazonaws.com

before_script:
  - docker info
  - bash ./scripts/private-repo.sh

build:
  tags:
    - shell
  rules:
    - if: $CI_MERGE_REQUEST_ID
  stage: build
  script:
    - eval `keychain --eval id_rsa`
    - DOCKER_BUILDKIT=1 docker build --ssh default --pull -t $DOCKER_REGISTRY/$CONTAINER_IMAGE:$CI_MERGE_REQUEST_ID .

build:
  tags:
    - shell
  rules:
    - if: $CI_COMMIT_BRANCH
  stage: build
  script:
    - eval `keychain --eval id_rsa`
    - DOCKER_BUILDKIT=1 docker build --ssh default --pull -t $DOCKER_REGISTRY/$CONTAINER_IMAGE:$CI_COMMIT_BRANCH .
    - docker push $DOCKER_REGISTRY/$CONTAINER_IMAGE:$CI_COMMIT_BRANCH
