#!/usr/bin/env bash
# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the Espresso library.

set -euo pipefail

nix develop .#staticShell -c cargo build --profile=release-lto

# Needed sudo to make this run on Ubuntu 20.04.4LTS and docker 20.10.14, build a224086349
sudo docker build . -f docker/address-book.Dockerfile -t ghcr.io/espressosystems/espresso/address-book:main
sudo docker build . -f docker/faucet.Dockerfile -t ghcr.io/espressosystems/espresso/faucet:main
sudo docker build . -f docker/validator.Dockerfile -t ghcr.io/espressosystems/espresso/validator:main
sudo docker build . -f docker/random-wallet.Dockerfile -t ghcr.io/espressosystems/espresso/random-wallet:main
