@startuml

concise "Phaselock" as PL

concise "Replica 1" as R1
concise "Replica 2" as R2
concise "Replica 3" as R3
concise "Replica 4" as R4
concise "Replica 5" as R5
concise "Replica 6" as R6
concise "Replica 7" as R7

@PL
0 is "..."
20 is View1
40 is View2
90 is View3
150 is View4
220 is "..."

'@R3
'10 is "Replica"
'20 is "Leader"
'30 is "Passive"

'Replica 3 is the leader for view 1

@30
R3 -[#red]> R1@+5: Prop v1
R3 -[#red]> R2@+6: Prop v1
R3 -[#red]> R4@+7: Prop v1
R3 -[#red]> R5@+8: Prop v1
R3 -[#red]> R6@+9: Prop v1
R3 -[#red]> R7@+10: Prop v1

'Replica 5 is the leader for view 2
'Replicas 6,7,2 are part of the committee
@50
R6 -[#blue]> R5@+5: vote6
R7 -[#blue]> R5@+15: vote7
R2 -[#blue]> R5@+10: vote2

@70
R5 -[#red]> R1@+5: Prop v2
R5 -[#red]> R2@+6: Prop v2
R5 -[#red]> R4@+7: Prop v2
R5 -[#red]> R3@+8: Prop v2
R5 -[#red]> R6@+9: Prop v2
R5 -[#red]> R7@+10: Prop v2

'Replica 2 is the leader for view 3
'Replicas 1,3 are part of the committee
@100

R1 -[#blue]> R2@+3: vote1
R3 -[#blue]> R2@+7: vote3

@120

R2 -[#red]> R1@+5: Prop v3
R2 -[#red]> R3@+6: Prop v2
R2 -[#red]> R4@+7: Prop v2
R2 -[#red]> R5@+8: Prop v2
R2 -[#red]> R6@+9: Prop v2
R2 -[#red]> R7@+10: Prop v2

'Replica 7 is the leader for view 4
'Replicas 3,4,5 are part of the committee

@160

R3 -[#blue]> R7@+10: vote3
R4 -[#blue]> R7@+20: vote4
R5 -[#blue]> R7@+17: vote5

@190

R7 -[#red]> R1@+5: Prop v4
R7 -[#red]> R2@+6: Prop v4
R7 -[#red]> R4@+7: Prop v4
R7 -[#red]> R5@+8: Prop v4
R7 -[#red]> R6@+9: Prop v4
R7 -[#red]> R3@+10: Prop v4

' TODO plantuml (nix-shell) crashes here
'highlight 20 to 40 #Gold: R3 is the Leader
'highlight 40 to 90 #lightblue : R5 is the Leader
'highlight 90 to 150 #Gold : R2 is the Leader
'highlight 150 to 220 #lightblue : R7 is the Leader

@enduml



