# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the Espresso library.

name: Cargo Audit

on:
  push:
    branches:
      - main
      - release-*
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  pull_request:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

env:
  RUST_LOG: info,libp2p=off

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Audit
        run: cargo audit
